name: BukkitCalculator
version: dev-1
description: An in-game calculator, with some shortcuts for Minecraft-specific calculations.
authors: [JJJollyjim, printfn]
main: com.kwiius.BukkitCalculator.BukkitCalculator
commands:
    c:
        aliases: [calc, calculate]
        description: Calculate a mathematical equation
        usage: /calc 5+5 (* = multiply, / = divide, % = modulo, ^ = power)